version: '3.9'

volumes:
  nextcloud_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/storage
  nextcloud_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DIR}/data/nextcloud
  nextcloud_conf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DIR}/config/nextcloud
  mariadb_conf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DIR}/config/mariadb
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DIR}/data/mariadb

services:

  nextcloud_notify_push:
    build: ./notify_push
    container_name: nextcloud-notify-push
    hostname: push
    restart: always
    volumes:
      - nextcloud_data:/var/www/html:ro

  nextcloud_app:
    image: nextcloud:fpm-opt
    container_name: nextcloud-app
    hostname: app
    restart: always
    volumes:
      # upload files to tmpfs.
      # see: tempdirectory (nc) and upload_tmp_dir (php) config parameters
      #- /tmp:/tmp
      - nextcloud_conf:/usr/local/etc
      - nextcloud_data:/var/www/html
      - nextcloud_storage:/var/www/html/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - REDIS_HOST=${REDIS_HOST}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT}
      - PHP_UPLOAD_LIMIT=${PHP_UPLOAD_LIMIT}
    depends_on:
      - db
      - redis
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
        window: 20s
      placement:
        constraints:
          - node.role==manager

  nextcloud_web:
    image: clearlinux/nginx
    #build: ./nginx
    container_name: nextcloud-web
    hostname: nextcloud
    restart: always
    depends_on:
      - app
    ports:
      - ${NC_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - nextcloud_data:/var/www/html
      - nextcloud_storage:/var/www/html/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
        window: 20s
      placement:
        constraints:
          - node.role==manager

  nextcloud_db:
    image: clearlinux/mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed --disable-log-bin
    container_name: nextcloud-db
    hostname: ${MYSQL_HOST}
    restart: always
    volumes:
      #- mariadb_conf:/etc/mysql/mariadb.conf.d
      - mariadb_conf:/usr/share/defaults/mariadb/my.cnf.d/
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  nextcloud_redis:
    image: clearlinux/redis
    hostname: ${REDIS_HOST}
    container_name: nextcloud-redis
    restart: always

